### PR TITLE
Fixed quotation error. Refactored code to remove duplication of data.

### LINKED ISSUE #14: Add JSEncode for ignoring ' and " characters in query .

### LINKED ISSUE #16: App breaking
Check app for song Dont Let Me Down. Page reloading when trying to play. Therefore adding UK TOP 40 to the playlist using play option is also crashing.

### PR DESCRIPTION
**Pull request by sksin28**
Fixed quotation error. resolved #14 resolved #16 
Refactored code to remove duplication of data.
Moved Chatroom code to Chatroom.js

### CODE REVIEW

File: public/javascripts/configuration.js [hunk 1]
```diff
@@ -3,8 +3,8 @@
  */
 
 var lanify_protocol = "http";
-var lanify_address = "192.168.109.66";
-var lanify_port = "3000";
+var lanify_address = "192.168.109.211";
```
Comment (direwolf424) [inline public/javascripts/configuration.js:6]: dont change the IP .

Comment (sksin28) [inline public/javascripts/configuration.js]: Sorry. Will take care of it.

Comment (sksin28) [inline public/javascripts/configuration.js:6]: Sorry. Will take care of it next time.
